[package]
name = "stuos"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
foldhash = {version="0.2.0", default-features=false}
hashbrown = {version="0.17.1"}
spin = {version = "0.12.3", default-features = false, features = ["spin_mutex", "mutex"] }

[build-dependencies]
bindgen = "0.73.2"
