/* automatically generated by rust-bindgen 0.73.2 */

pub const INT8_MIN: i32 = -128;
pub const INT8_MAX: u32 = 127;
pub const UINT8_MAX: u32 = 255;
pub const INT16_MIN: i32 = -32768;
pub const INT16_MAX: u32 = 32767;
pub const UINT16_MAX: u32 = 65535;
pub const INT32_MIN: i32 = -2147483648;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST8_MAX: u32 = 127;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST8_MAX: u32 = 127;
pub const UINT_FAST8_MAX: u32 = 255;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const INTMAX_MIN: i64 = -9223372036854775808;
pub const INTMAX_MAX: u64 = 9223372036854775807;
pub const UINTMAX_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIZE_MAX: i32 = -1;
pub const RLIMIT_DATA: u32 = 0;
pub const SIG_BLOCK: u32 = 0;
pub const SIG_UNBLOCK: u32 = 1;
pub const SIG_SETMASK: u32 = 2;
pub const SIGINT: u32 = 0;
pub const SIGKILL: u32 = 1;
pub const DT_UNKNOWN: u32 = 0;
pub const DT_FIFO: u32 = 1;
pub const DT_CHR: u32 = 2;
pub const DT_DIR: u32 = 4;
pub const DT_BLK: u32 = 6;
pub const DT_REG: u32 = 8;
pub const DT_LNK: u32 = 10;
pub const DT_SOCK: u32 = 12;
pub const DT_WHT: u32 = 14;
pub const S_IFMT: u32 = 61440;
pub const S_IFDIR: u32 = 16384;
pub const S_IFBLK: u32 = 24576;
pub const S_IFREG: u32 = 32768;
pub const O_RDONLY: u32 = 1;
pub const O_WRONLY: u32 = 1;
pub const O_RDWR: u32 = 3;
pub const O_APPEND: u32 = 4;
pub const O_CREAT: u32 = 8;
pub const O_DIRECTORY: u32 = 16;
pub const O_TRUNC: u32 = 32;
pub const O_NONBLOCK: u32 = 64;
pub const ICANON: u32 = 2;
pub type int_least8_t = ::core::ffi::c_schar;
pub type uint_least8_t = ::core::ffi::c_uchar;
pub type int_least16_t = ::core::ffi::c_short;
pub type uint_least16_t = ::core::ffi::c_ushort;
pub type int_least32_t = ::core::ffi::c_int;
pub type uint_least32_t = ::core::ffi::c_uint;
pub type int_least64_t = ::core::ffi::c_longlong;
pub type uint_least64_t = ::core::ffi::c_ulonglong;
pub type int_fast8_t = ::core::ffi::c_schar;
pub type uint_fast8_t = ::core::ffi::c_uchar;
pub type int_fast16_t = ::core::ffi::c_int;
pub type uint_fast16_t = ::core::ffi::c_uint;
pub type int_fast32_t = ::core::ffi::c_int;
pub type uint_fast32_t = ::core::ffi::c_uint;
pub type int_fast64_t = ::core::ffi::c_longlong;
pub type uint_fast64_t = ::core::ffi::c_ulonglong;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
pub type rlim_t = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rlimit {
    pub rlim_cur: rlim_t,
    pub rlim_max: rlim_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rlimit"][::core::mem::size_of::<rlimit>() - 16usize];
    ["Alignment of rlimit"][::core::mem::align_of::<rlimit>() - 8usize];
    ["Offset of field: rlimit::rlim_cur"][::core::mem::offset_of!(rlimit, rlim_cur) - 0usize];
    ["Offset of field: rlimit::rlim_max"][::core::mem::offset_of!(rlimit, rlim_max) - 8usize];
};
pub type pid_t = ::core::ffi::c_int;
pub type gid_t = ::core::ffi::c_uint;
pub type uid_t = ::core::ffi::c_uint;
pub type mode_t = ::core::ffi::c_uint;
pub type dev_t = ::core::ffi::c_ulong;
pub type ino_t = u64;
pub type off_t = i64;
pub type nlink_t = ::core::ffi::c_ulong;
pub type sigset_t = u32;
pub type sig_atomic_t = ::core::ffi::c_int;
pub type sighandler_t = ::core::option::Option<unsafe extern "C" fn(arg1: ::core::ffi::c_int)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dirent {
    pub d_ino: ino_t,
    pub d_type: ::core::ffi::c_uchar,
    pub d_name: [::core::ffi::c_char; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dirent"][::core::mem::size_of::<dirent>() - 272usize];
    ["Alignment of dirent"][::core::mem::align_of::<dirent>() - 8usize];
    ["Offset of field: dirent::d_ino"][::core::mem::offset_of!(dirent, d_ino) - 0usize];
    ["Offset of field: dirent::d_type"][::core::mem::offset_of!(dirent, d_type) - 8usize];
    ["Offset of field: dirent::d_name"][::core::mem::offset_of!(dirent, d_name) - 9usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct stat {
    pub st_ino: ino_t,
    pub st_mode: mode_t,
    pub st_uid: uid_t,
    pub st_gid: gid_t,
    pub st_size: off_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of stat"][::core::mem::size_of::<stat>() - 32usize];
    ["Alignment of stat"][::core::mem::align_of::<stat>() - 8usize];
    ["Offset of field: stat::st_ino"][::core::mem::offset_of!(stat, st_ino) - 0usize];
    ["Offset of field: stat::st_mode"][::core::mem::offset_of!(stat, st_mode) - 8usize];
    ["Offset of field: stat::st_uid"][::core::mem::offset_of!(stat, st_uid) - 12usize];
    ["Offset of field: stat::st_gid"][::core::mem::offset_of!(stat, st_gid) - 16usize];
    ["Offset of field: stat::st_size"][::core::mem::offset_of!(stat, st_size) - 24usize];
};
pub type cc_t = ::core::ffi::c_uchar;
pub type speed_t = ::core::ffi::c_uint;
pub type tcflag_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct termios {
    pub c_iflag: tcflag_t,
    pub c_oflag: tcflag_t,
    pub c_cflag: tcflag_t,
    pub c_lflag: tcflag_t,
    pub c_cc: [cc_t; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of termios"][::core::mem::size_of::<termios>() - 48usize];
    ["Alignment of termios"][::core::mem::align_of::<termios>() - 4usize];
    ["Offset of field: termios::c_iflag"][::core::mem::offset_of!(termios, c_iflag) - 0usize];
    ["Offset of field: termios::c_oflag"][::core::mem::offset_of!(termios, c_oflag) - 4usize];
    ["Offset of field: termios::c_cflag"][::core::mem::offset_of!(termios, c_cflag) - 8usize];
    ["Offset of field: termios::c_lflag"][::core::mem::offset_of!(termios, c_lflag) - 12usize];
    ["Offset of field: termios::c_cc"][::core::mem::offset_of!(termios, c_cc) - 16usize];
};
unsafe extern "C" {
    pub fn do_syscall(data: *mut ::core::ffi::c_void, syscall_number: u64);
}
pub const HALT_SYSCALL: u64 = 0;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HaltSyscallData {
    pub exit_code: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of HaltSyscallData"][::core::mem::size_of::<HaltSyscallData>() - 1usize];
    ["Alignment of HaltSyscallData"][::core::mem::align_of::<HaltSyscallData>() - 1usize];
    ["Offset of field: HaltSyscallData::exit_code"]
        [::core::mem::offset_of!(HaltSyscallData, exit_code) - 0usize];
};
pub const GET_UPTIME_MS_SYSCALL: u64 = 7;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GetUptimeMsData {
    pub ms: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GetUptimeMsData"][::core::mem::size_of::<GetUptimeMsData>() - 8usize];
    ["Alignment of GetUptimeMsData"][::core::mem::align_of::<GetUptimeMsData>() - 8usize];
    ["Offset of field: GetUptimeMsData::ms"][::core::mem::offset_of!(GetUptimeMsData, ms) - 0usize];
};
pub const REQUEST_PAGE_SYSCALL: u64 = 11;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RequestPageData {
    pub page_virt_addr: *mut ::core::ffi::c_void,
    pub err: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RequestPageData"][::core::mem::size_of::<RequestPageData>() - 16usize];
    ["Alignment of RequestPageData"][::core::mem::align_of::<RequestPageData>() - 8usize];
    ["Offset of field: RequestPageData::page_virt_addr"]
        [::core::mem::offset_of!(RequestPageData, page_virt_addr) - 0usize];
    ["Offset of field: RequestPageData::err"]
        [::core::mem::offset_of!(RequestPageData, err) - 8usize];
};
pub const GET_HEAP_START_SYSCALL: u64 = 12;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GetHeapStartData {
    pub output: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GetHeapStartData"][::core::mem::size_of::<GetHeapStartData>() - 8usize];
    ["Alignment of GetHeapStartData"][::core::mem::align_of::<GetHeapStartData>() - 8usize];
    ["Offset of field: GetHeapStartData::output"]
        [::core::mem::offset_of!(GetHeapStartData, output) - 0usize];
};
pub const WRITE_FD_SYSCALL: u64 = 13;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WriteFDData {
    pub file_descriptor_number: ::core::ffi::c_int,
    pub buffer: *const ::core::ffi::c_void,
    pub num_bytes: usize,
    pub num_bytes_actually_written: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WriteFDData"][::core::mem::size_of::<WriteFDData>() - 32usize];
    ["Alignment of WriteFDData"][::core::mem::align_of::<WriteFDData>() - 8usize];
    ["Offset of field: WriteFDData::file_descriptor_number"]
        [::core::mem::offset_of!(WriteFDData, file_descriptor_number) - 0usize];
    ["Offset of field: WriteFDData::buffer"][::core::mem::offset_of!(WriteFDData, buffer) - 8usize];
    ["Offset of field: WriteFDData::num_bytes"]
        [::core::mem::offset_of!(WriteFDData, num_bytes) - 16usize];
    ["Offset of field: WriteFDData::num_bytes_actually_written"]
        [::core::mem::offset_of!(WriteFDData, num_bytes_actually_written) - 24usize];
};
pub const OPEN_FILE_SYSCALL: u64 = 14;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OpenFileData {
    pub path: *const ::core::ffi::c_char,
    pub output_file_descriptor_number: ::core::ffi::c_int,
    pub open_flags: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OpenFileData"][::core::mem::size_of::<OpenFileData>() - 16usize];
    ["Alignment of OpenFileData"][::core::mem::align_of::<OpenFileData>() - 8usize];
    ["Offset of field: OpenFileData::path"][::core::mem::offset_of!(OpenFileData, path) - 0usize];
    ["Offset of field: OpenFileData::output_file_descriptor_number"]
        [::core::mem::offset_of!(OpenFileData, output_file_descriptor_number) - 8usize];
    ["Offset of field: OpenFileData::open_flags"]
        [::core::mem::offset_of!(OpenFileData, open_flags) - 12usize];
};
pub const READ_FD_SYSCALL: u64 = 15;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ReadFDData {
    pub file_descriptor_number: ::core::ffi::c_int,
    pub buffer: *mut ::core::ffi::c_void,
    pub num_bytes: usize,
    pub num_bytes_actually_read: *mut usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ReadFDData"][::core::mem::size_of::<ReadFDData>() - 32usize];
    ["Alignment of ReadFDData"][::core::mem::align_of::<ReadFDData>() - 8usize];
    ["Offset of field: ReadFDData::file_descriptor_number"]
        [::core::mem::offset_of!(ReadFDData, file_descriptor_number) - 0usize];
    ["Offset of field: ReadFDData::buffer"][::core::mem::offset_of!(ReadFDData, buffer) - 8usize];
    ["Offset of field: ReadFDData::num_bytes"]
        [::core::mem::offset_of!(ReadFDData, num_bytes) - 16usize];
    ["Offset of field: ReadFDData::num_bytes_actually_read"]
        [::core::mem::offset_of!(ReadFDData, num_bytes_actually_read) - 24usize];
};
pub const LSEEK_FD_SYSCALL: u64 = 16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LseekFDData {
    pub file_descriptor_number: ::core::ffi::c_int,
    pub offset: i64,
    pub whence: ::core::ffi::c_int,
    pub actual_offset: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LseekFDData"][::core::mem::size_of::<LseekFDData>() - 32usize];
    ["Alignment of LseekFDData"][::core::mem::align_of::<LseekFDData>() - 8usize];
    ["Offset of field: LseekFDData::file_descriptor_number"]
        [::core::mem::offset_of!(LseekFDData, file_descriptor_number) - 0usize];
    ["Offset of field: LseekFDData::offset"][::core::mem::offset_of!(LseekFDData, offset) - 8usize];
    ["Offset of field: LseekFDData::whence"]
        [::core::mem::offset_of!(LseekFDData, whence) - 16usize];
    ["Offset of field: LseekFDData::actual_offset"]
        [::core::mem::offset_of!(LseekFDData, actual_offset) - 24usize];
};
pub const CLOSE_FD_SYSCALL: u64 = 17;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CloseFDData {
    pub file_descriptor_number: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CloseFDData"][::core::mem::size_of::<CloseFDData>() - 4usize];
    ["Alignment of CloseFDData"][::core::mem::align_of::<CloseFDData>() - 4usize];
    ["Offset of field: CloseFDData::file_descriptor_number"]
        [::core::mem::offset_of!(CloseFDData, file_descriptor_number) - 0usize];
};
pub const FORK_SYSCALL: u64 = 18;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ForkData {
    pub pid: *mut ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ForkData"][::core::mem::size_of::<ForkData>() - 8usize];
    ["Alignment of ForkData"][::core::mem::align_of::<ForkData>() - 8usize];
    ["Offset of field: ForkData::pid"][::core::mem::offset_of!(ForkData, pid) - 0usize];
};
pub const GET_PGRP_SYSCALL: u64 = 19;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GetPgrpData {
    pub result: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GetPgrpData"][::core::mem::size_of::<GetPgrpData>() - 4usize];
    ["Alignment of GetPgrpData"][::core::mem::align_of::<GetPgrpData>() - 4usize];
    ["Offset of field: GetPgrpData::result"][::core::mem::offset_of!(GetPgrpData, result) - 0usize];
};
pub const GET_PID_SYSCALL: u64 = 20;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GetPidData {
    pub result: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GetPidData"][::core::mem::size_of::<GetPidData>() - 4usize];
    ["Alignment of GetPidData"][::core::mem::align_of::<GetPidData>() - 4usize];
    ["Offset of field: GetPidData::result"][::core::mem::offset_of!(GetPidData, result) - 0usize];
};
pub const DUPFD_SYSCALL: u64 = 21;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DupFdData {
    pub fildes: ::core::ffi::c_int,
    pub min_new_fd: ::core::ffi::c_int,
    pub result_fd: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of DupFdData"][::core::mem::size_of::<DupFdData>() - 12usize];
    ["Alignment of DupFdData"][::core::mem::align_of::<DupFdData>() - 4usize];
    ["Offset of field: DupFdData::fildes"][::core::mem::offset_of!(DupFdData, fildes) - 0usize];
    ["Offset of field: DupFdData::min_new_fd"]
        [::core::mem::offset_of!(DupFdData, min_new_fd) - 4usize];
    ["Offset of field: DupFdData::result_fd"]
        [::core::mem::offset_of!(DupFdData, result_fd) - 8usize];
};
pub const GET_CWD_SYSCALL: u64 = 22;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GetCwdData {
    pub buf: *mut ::core::ffi::c_char,
    pub size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GetCwdData"][::core::mem::size_of::<GetCwdData>() - 16usize];
    ["Alignment of GetCwdData"][::core::mem::align_of::<GetCwdData>() - 8usize];
    ["Offset of field: GetCwdData::buf"][::core::mem::offset_of!(GetCwdData, buf) - 0usize];
    ["Offset of field: GetCwdData::size"][::core::mem::offset_of!(GetCwdData, size) - 8usize];
};
pub const CHDIR_SYSCALL: u64 = 23;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ChdirData {
    pub path: *const ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ChdirData"][::core::mem::size_of::<ChdirData>() - 8usize];
    ["Alignment of ChdirData"][::core::mem::align_of::<ChdirData>() - 8usize];
    ["Offset of field: ChdirData::path"][::core::mem::offset_of!(ChdirData, path) - 0usize];
};
pub const EXECVE_SYSCALL: u64 = 24;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ExecveData {
    pub filename: *const ::core::ffi::c_char,
    pub argv: *const *mut ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ExecveData"][::core::mem::size_of::<ExecveData>() - 16usize];
    ["Alignment of ExecveData"][::core::mem::align_of::<ExecveData>() - 8usize];
    ["Offset of field: ExecveData::filename"]
        [::core::mem::offset_of!(ExecveData, filename) - 0usize];
    ["Offset of field: ExecveData::argv"][::core::mem::offset_of!(ExecveData, argv) - 8usize];
};
pub const WNOHANG: _bindgen_ty_1 = 1;
pub const WUNTRACED: _bindgen_ty_1 = 2;
pub const WCONTINUED: _bindgen_ty_1 = 4;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const WAIT_SYSCALL: u64 = 25;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WaitData {
    pub pid: ::core::ffi::c_int,
    pub status: *mut ::core::ffi::c_int,
    pub options: ::core::ffi::c_int,
    pub output_pid: *mut ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WaitData"][::core::mem::size_of::<WaitData>() - 32usize];
    ["Alignment of WaitData"][::core::mem::align_of::<WaitData>() - 8usize];
    ["Offset of field: WaitData::pid"][::core::mem::offset_of!(WaitData, pid) - 0usize];
    ["Offset of field: WaitData::status"][::core::mem::offset_of!(WaitData, status) - 8usize];
    ["Offset of field: WaitData::options"][::core::mem::offset_of!(WaitData, options) - 16usize];
    ["Offset of field: WaitData::output_pid"]
        [::core::mem::offset_of!(WaitData, output_pid) - 24usize];
};
pub const ISATTY_SYSCALL: u64 = 26;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IsattyData {
    pub fd: ::core::ffi::c_int,
    pub result: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IsattyData"][::core::mem::size_of::<IsattyData>() - 8usize];
    ["Alignment of IsattyData"][::core::mem::align_of::<IsattyData>() - 4usize];
    ["Offset of field: IsattyData::fd"][::core::mem::offset_of!(IsattyData, fd) - 0usize];
    ["Offset of field: IsattyData::result"][::core::mem::offset_of!(IsattyData, result) - 4usize];
};
pub const PIPE_SYSCALL: u64 = 27;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PipeData {
    pub fd_a: ::core::ffi::c_int,
    pub fd_b: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PipeData"][::core::mem::size_of::<PipeData>() - 8usize];
    ["Alignment of PipeData"][::core::mem::align_of::<PipeData>() - 4usize];
    ["Offset of field: PipeData::fd_a"][::core::mem::offset_of!(PipeData, fd_a) - 0usize];
    ["Offset of field: PipeData::fd_b"][::core::mem::offset_of!(PipeData, fd_b) - 4usize];
};
pub const STAT_SYSCALL: u64 = 28;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct StatData {
    pub result: stat,
    pub path: *const ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of StatData"][::core::mem::size_of::<StatData>() - 40usize];
    ["Alignment of StatData"][::core::mem::align_of::<StatData>() - 8usize];
    ["Offset of field: StatData::result"][::core::mem::offset_of!(StatData, result) - 0usize];
    ["Offset of field: StatData::path"][::core::mem::offset_of!(StatData, path) - 32usize];
};
pub const SIGPROCMASK_SYSCALL: u64 = 29;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SigProcMaskData {
    pub how: ::core::ffi::c_int,
    pub set: *const sigset_t,
    pub oldset: sigset_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SigProcMaskData"][::core::mem::size_of::<SigProcMaskData>() - 24usize];
    ["Alignment of SigProcMaskData"][::core::mem::align_of::<SigProcMaskData>() - 8usize];
    ["Offset of field: SigProcMaskData::how"]
        [::core::mem::offset_of!(SigProcMaskData, how) - 0usize];
    ["Offset of field: SigProcMaskData::set"]
        [::core::mem::offset_of!(SigProcMaskData, set) - 8usize];
    ["Offset of field: SigProcMaskData::oldset"]
        [::core::mem::offset_of!(SigProcMaskData, oldset) - 16usize];
};
pub const SETSIGNALHANDLER_SYSCALL: u64 = 30;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SetSignalHandlerData {
    pub signal_number: ::core::ffi::c_int,
    pub handler: sighandler_t,
    pub old_handler: sighandler_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SetSignalHandlerData"][::core::mem::size_of::<SetSignalHandlerData>() - 24usize];
    ["Alignment of SetSignalHandlerData"][::core::mem::align_of::<SetSignalHandlerData>() - 8usize];
    ["Offset of field: SetSignalHandlerData::signal_number"]
        [::core::mem::offset_of!(SetSignalHandlerData, signal_number) - 0usize];
    ["Offset of field: SetSignalHandlerData::handler"]
        [::core::mem::offset_of!(SetSignalHandlerData, handler) - 8usize];
    ["Offset of field: SetSignalHandlerData::old_handler"]
        [::core::mem::offset_of!(SetSignalHandlerData, old_handler) - 16usize];
};
pub const KILL_SYSCALL: u64 = 31;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KillData {
    pub pid: pid_t,
    pub sig: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KillData"][::core::mem::size_of::<KillData>() - 8usize];
    ["Alignment of KillData"][::core::mem::align_of::<KillData>() - 4usize];
    ["Offset of field: KillData::pid"][::core::mem::offset_of!(KillData, pid) - 0usize];
    ["Offset of field: KillData::sig"][::core::mem::offset_of!(KillData, sig) - 4usize];
};
pub const TCGETATTR_SYSCALL: u64 = 32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TcGetAttrData {
    pub fd: ::core::ffi::c_int,
    pub output: termios,
    pub err: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of TcGetAttrData"][::core::mem::size_of::<TcGetAttrData>() - 56usize];
    ["Alignment of TcGetAttrData"][::core::mem::align_of::<TcGetAttrData>() - 4usize];
    ["Offset of field: TcGetAttrData::fd"][::core::mem::offset_of!(TcGetAttrData, fd) - 0usize];
    ["Offset of field: TcGetAttrData::output"]
        [::core::mem::offset_of!(TcGetAttrData, output) - 4usize];
    ["Offset of field: TcGetAttrData::err"][::core::mem::offset_of!(TcGetAttrData, err) - 52usize];
};
pub const SETRLIMIT_SYSCALL: u64 = 33;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SetRLimitData {
    pub resource: ::core::ffi::c_int,
    pub limit: rlimit,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SetRLimitData"][::core::mem::size_of::<SetRLimitData>() - 24usize];
    ["Alignment of SetRLimitData"][::core::mem::align_of::<SetRLimitData>() - 8usize];
    ["Offset of field: SetRLimitData::resource"]
        [::core::mem::offset_of!(SetRLimitData, resource) - 0usize];
    ["Offset of field: SetRLimitData::limit"]
        [::core::mem::offset_of!(SetRLimitData, limit) - 8usize];
};
pub const GETRLIMIT_SYSCALL: u64 = 34;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GetRLimitData {
    pub resource: ::core::ffi::c_int,
    pub limit: rlimit,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GetRLimitData"][::core::mem::size_of::<GetRLimitData>() - 24usize];
    ["Alignment of GetRLimitData"][::core::mem::align_of::<GetRLimitData>() - 8usize];
    ["Offset of field: GetRLimitData::resource"]
        [::core::mem::offset_of!(GetRLimitData, resource) - 0usize];
    ["Offset of field: GetRLimitData::limit"]
        [::core::mem::offset_of!(GetRLimitData, limit) - 8usize];
};
pub const YIELD_SYSCALL: u64 = 35;
