/* automatically generated by rust-bindgen 0.73.2 */

pub const INT8_MIN: i32 = -128;
pub const INT8_MAX: u32 = 127;
pub const UINT8_MAX: u32 = 255;
pub const INT16_MIN: i32 = -32768;
pub const INT16_MAX: u32 = 32767;
pub const UINT16_MAX: u32 = 65535;
pub const INT32_MIN: i32 = -2147483648;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST8_MAX: u32 = 127;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST8_MAX: u32 = 127;
pub const UINT_FAST8_MAX: u32 = 255;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const INTMAX_MIN: i64 = -9223372036854775808;
pub const INTMAX_MAX: u64 = 9223372036854775807;
pub const UINTMAX_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIZE_MAX: i32 = -1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const LIMINE_H: u32 = 1;
pub const LIMINE_MEDIA_TYPE_GENERIC: u32 = 0;
pub const LIMINE_MEDIA_TYPE_OPTICAL: u32 = 1;
pub const LIMINE_MEDIA_TYPE_TFTP: u32 = 2;
pub const LIMINE_FIRMWARE_TYPE_X86BIOS: u32 = 0;
pub const LIMINE_FIRMWARE_TYPE_EFI32: u32 = 1;
pub const LIMINE_FIRMWARE_TYPE_EFI64: u32 = 2;
pub const LIMINE_FIRMWARE_TYPE_SBI: u32 = 3;
pub const LIMINE_FRAMEBUFFER_RGB: u32 = 1;
pub const LIMINE_FLANTERM_FB_ROTATE_0: u32 = 0;
pub const LIMINE_FLANTERM_FB_ROTATE_90: u32 = 1;
pub const LIMINE_FLANTERM_FB_ROTATE_180: u32 = 2;
pub const LIMINE_FLANTERM_FB_ROTATE_270: u32 = 3;
pub const LIMINE_PAGING_MODE_X86_64_4LVL: u32 = 0;
pub const LIMINE_PAGING_MODE_X86_64_5LVL: u32 = 1;
pub const LIMINE_PAGING_MODE_X86_64_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_X86_64_DEFAULT: u32 = 0;
pub const LIMINE_PAGING_MODE_AARCH64_4LVL: u32 = 0;
pub const LIMINE_PAGING_MODE_AARCH64_5LVL: u32 = 1;
pub const LIMINE_PAGING_MODE_AARCH64_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_AARCH64_DEFAULT: u32 = 0;
pub const LIMINE_PAGING_MODE_RISCV_SV39: u32 = 0;
pub const LIMINE_PAGING_MODE_RISCV_SV48: u32 = 1;
pub const LIMINE_PAGING_MODE_RISCV_SV57: u32 = 2;
pub const LIMINE_PAGING_MODE_RISCV_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_RISCV_DEFAULT: u32 = 1;
pub const LIMINE_PAGING_MODE_LOONGARCH_4LVL: u32 = 0;
pub const LIMINE_PAGING_MODE_LOONGARCH_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_LOONGARCH_DEFAULT: u32 = 0;
pub const LIMINE_MP_RESPONSE_X86_64_X2APIC: u32 = 1;
pub const LIMINE_MP_REQUEST_X86_64_X2APIC: u32 = 1;
pub const LIMINE_MEMMAP_USABLE: u32 = 0;
pub const LIMINE_MEMMAP_RESERVED: u32 = 1;
pub const LIMINE_MEMMAP_ACPI_RECLAIMABLE: u32 = 2;
pub const LIMINE_MEMMAP_ACPI_NVS: u32 = 3;
pub const LIMINE_MEMMAP_BAD_MEMORY: u32 = 4;
pub const LIMINE_MEMMAP_BOOTLOADER_RECLAIMABLE: u32 = 5;
pub const LIMINE_MEMMAP_EXECUTABLE_AND_MODULES: u32 = 6;
pub const LIMINE_MEMMAP_FRAMEBUFFER: u32 = 7;
pub const LIMINE_MEMMAP_RESERVED_MAPPED: u32 = 8;
pub const LIMINE_INTERNAL_MODULE_REQUIRED: u32 = 1;
pub const LIMINE_INTERNAL_MODULE_COMPRESSED: u32 = 2;
pub const LIMINE_TPM_EVENT_LOG_FORMAT_TCG_1_2: u32 = 1;
pub const LIMINE_TPM_EVENT_LOG_FORMAT_TCG_2: u32 = 2;
pub type int_least8_t = ::core::ffi::c_schar;
pub type uint_least8_t = ::core::ffi::c_uchar;
pub type int_least16_t = ::core::ffi::c_short;
pub type uint_least16_t = ::core::ffi::c_ushort;
pub type int_least32_t = ::core::ffi::c_int;
pub type uint_least32_t = ::core::ffi::c_uint;
pub type int_least64_t = ::core::ffi::c_longlong;
pub type uint_least64_t = ::core::ffi::c_ulonglong;
pub type int_fast8_t = ::core::ffi::c_schar;
pub type uint_fast8_t = ::core::ffi::c_uchar;
pub type int_fast16_t = ::core::ffi::c_int;
pub type uint_fast16_t = ::core::ffi::c_uint;
pub type int_fast32_t = ::core::ffi::c_int;
pub type uint_fast32_t = ::core::ffi::c_uint;
pub type int_fast64_t = ::core::ffi::c_longlong;
pub type uint_fast64_t = ::core::ffi::c_ulonglong;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_uuid {
    pub a: u32,
    pub b: u16,
    pub c: u16,
    pub d: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_uuid"][::core::mem::size_of::<limine_uuid>() - 16usize];
    ["Alignment of limine_uuid"][::core::mem::align_of::<limine_uuid>() - 4usize];
    ["Offset of field: limine_uuid::a"][::core::mem::offset_of!(limine_uuid, a) - 0usize];
    ["Offset of field: limine_uuid::b"][::core::mem::offset_of!(limine_uuid, b) - 4usize];
    ["Offset of field: limine_uuid::c"][::core::mem::offset_of!(limine_uuid, c) - 6usize];
    ["Offset of field: limine_uuid::d"][::core::mem::offset_of!(limine_uuid, d) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_file {
    pub revision: u64,
    pub address: *mut ::core::ffi::c_void,
    pub size: u64,
    pub path: *mut ::core::ffi::c_char,
    pub string: *mut ::core::ffi::c_char,
    pub media_type: u32,
    pub unused: u32,
    pub tftp_ipv4: [u8; 4usize],
    pub tftp_port: u32,
    pub partition_index: u32,
    pub mbr_disk_id: u32,
    pub gpt_disk_uuid: limine_uuid,
    pub gpt_part_uuid: limine_uuid,
    pub part_uuid: limine_uuid,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_file"][::core::mem::size_of::<limine_file>() - 112usize];
    ["Alignment of limine_file"][::core::mem::align_of::<limine_file>() - 8usize];
    ["Offset of field: limine_file::revision"]
        [::core::mem::offset_of!(limine_file, revision) - 0usize];
    ["Offset of field: limine_file::address"]
        [::core::mem::offset_of!(limine_file, address) - 8usize];
    ["Offset of field: limine_file::size"][::core::mem::offset_of!(limine_file, size) - 16usize];
    ["Offset of field: limine_file::path"][::core::mem::offset_of!(limine_file, path) - 24usize];
    ["Offset of field: limine_file::string"]
        [::core::mem::offset_of!(limine_file, string) - 32usize];
    ["Offset of field: limine_file::media_type"]
        [::core::mem::offset_of!(limine_file, media_type) - 40usize];
    ["Offset of field: limine_file::unused"]
        [::core::mem::offset_of!(limine_file, unused) - 44usize];
    ["Offset of field: limine_file::tftp_ipv4"]
        [::core::mem::offset_of!(limine_file, tftp_ipv4) - 48usize];
    ["Offset of field: limine_file::tftp_port"]
        [::core::mem::offset_of!(limine_file, tftp_port) - 52usize];
    ["Offset of field: limine_file::partition_index"]
        [::core::mem::offset_of!(limine_file, partition_index) - 56usize];
    ["Offset of field: limine_file::mbr_disk_id"]
        [::core::mem::offset_of!(limine_file, mbr_disk_id) - 60usize];
    ["Offset of field: limine_file::gpt_disk_uuid"]
        [::core::mem::offset_of!(limine_file, gpt_disk_uuid) - 64usize];
    ["Offset of field: limine_file::gpt_part_uuid"]
        [::core::mem::offset_of!(limine_file, gpt_part_uuid) - 80usize];
    ["Offset of field: limine_file::part_uuid"]
        [::core::mem::offset_of!(limine_file, part_uuid) - 96usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_info_response {
    pub revision: u64,
    pub name: *mut ::core::ffi::c_char,
    pub version: *mut ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_bootloader_info_response"]
        [::core::mem::size_of::<limine_bootloader_info_response>() - 24usize];
    ["Alignment of limine_bootloader_info_response"]
        [::core::mem::align_of::<limine_bootloader_info_response>() - 8usize];
    ["Offset of field: limine_bootloader_info_response::revision"]
        [::core::mem::offset_of!(limine_bootloader_info_response, revision) - 0usize];
    ["Offset of field: limine_bootloader_info_response::name"]
        [::core::mem::offset_of!(limine_bootloader_info_response, name) - 8usize];
    ["Offset of field: limine_bootloader_info_response::version"]
        [::core::mem::offset_of!(limine_bootloader_info_response, version) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_info_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_bootloader_info_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_bootloader_info_request"]
        [::core::mem::size_of::<limine_bootloader_info_request>() - 48usize];
    ["Alignment of limine_bootloader_info_request"]
        [::core::mem::align_of::<limine_bootloader_info_request>() - 8usize];
    ["Offset of field: limine_bootloader_info_request::id"]
        [::core::mem::offset_of!(limine_bootloader_info_request, id) - 0usize];
    ["Offset of field: limine_bootloader_info_request::revision"]
        [::core::mem::offset_of!(limine_bootloader_info_request, revision) - 32usize];
    ["Offset of field: limine_bootloader_info_request::response"]
        [::core::mem::offset_of!(limine_bootloader_info_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_cmdline_response {
    pub revision: u64,
    pub cmdline: *mut ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_executable_cmdline_response"]
        [::core::mem::size_of::<limine_executable_cmdline_response>() - 16usize];
    ["Alignment of limine_executable_cmdline_response"]
        [::core::mem::align_of::<limine_executable_cmdline_response>() - 8usize];
    ["Offset of field: limine_executable_cmdline_response::revision"]
        [::core::mem::offset_of!(limine_executable_cmdline_response, revision) - 0usize];
    ["Offset of field: limine_executable_cmdline_response::cmdline"]
        [::core::mem::offset_of!(limine_executable_cmdline_response, cmdline) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_cmdline_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_executable_cmdline_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_executable_cmdline_request"]
        [::core::mem::size_of::<limine_executable_cmdline_request>() - 48usize];
    ["Alignment of limine_executable_cmdline_request"]
        [::core::mem::align_of::<limine_executable_cmdline_request>() - 8usize];
    ["Offset of field: limine_executable_cmdline_request::id"]
        [::core::mem::offset_of!(limine_executable_cmdline_request, id) - 0usize];
    ["Offset of field: limine_executable_cmdline_request::revision"]
        [::core::mem::offset_of!(limine_executable_cmdline_request, revision) - 32usize];
    ["Offset of field: limine_executable_cmdline_request::response"]
        [::core::mem::offset_of!(limine_executable_cmdline_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_firmware_type_response {
    pub revision: u64,
    pub firmware_type: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_firmware_type_response"]
        [::core::mem::size_of::<limine_firmware_type_response>() - 16usize];
    ["Alignment of limine_firmware_type_response"]
        [::core::mem::align_of::<limine_firmware_type_response>() - 8usize];
    ["Offset of field: limine_firmware_type_response::revision"]
        [::core::mem::offset_of!(limine_firmware_type_response, revision) - 0usize];
    ["Offset of field: limine_firmware_type_response::firmware_type"]
        [::core::mem::offset_of!(limine_firmware_type_response, firmware_type) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_firmware_type_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_firmware_type_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_firmware_type_request"]
        [::core::mem::size_of::<limine_firmware_type_request>() - 48usize];
    ["Alignment of limine_firmware_type_request"]
        [::core::mem::align_of::<limine_firmware_type_request>() - 8usize];
    ["Offset of field: limine_firmware_type_request::id"]
        [::core::mem::offset_of!(limine_firmware_type_request, id) - 0usize];
    ["Offset of field: limine_firmware_type_request::revision"]
        [::core::mem::offset_of!(limine_firmware_type_request, revision) - 32usize];
    ["Offset of field: limine_firmware_type_request::response"]
        [::core::mem::offset_of!(limine_firmware_type_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_stack_size_response {
    pub revision: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_stack_size_response"]
        [::core::mem::size_of::<limine_stack_size_response>() - 8usize];
    ["Alignment of limine_stack_size_response"]
        [::core::mem::align_of::<limine_stack_size_response>() - 8usize];
    ["Offset of field: limine_stack_size_response::revision"]
        [::core::mem::offset_of!(limine_stack_size_response, revision) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_stack_size_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_stack_size_response,
    pub stack_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_stack_size_request"]
        [::core::mem::size_of::<limine_stack_size_request>() - 56usize];
    ["Alignment of limine_stack_size_request"]
        [::core::mem::align_of::<limine_stack_size_request>() - 8usize];
    ["Offset of field: limine_stack_size_request::id"]
        [::core::mem::offset_of!(limine_stack_size_request, id) - 0usize];
    ["Offset of field: limine_stack_size_request::revision"]
        [::core::mem::offset_of!(limine_stack_size_request, revision) - 32usize];
    ["Offset of field: limine_stack_size_request::response"]
        [::core::mem::offset_of!(limine_stack_size_request, response) - 40usize];
    ["Offset of field: limine_stack_size_request::stack_size"]
        [::core::mem::offset_of!(limine_stack_size_request, stack_size) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_hhdm_response {
    pub revision: u64,
    pub offset: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_hhdm_response"][::core::mem::size_of::<limine_hhdm_response>() - 16usize];
    ["Alignment of limine_hhdm_response"][::core::mem::align_of::<limine_hhdm_response>() - 8usize];
    ["Offset of field: limine_hhdm_response::revision"]
        [::core::mem::offset_of!(limine_hhdm_response, revision) - 0usize];
    ["Offset of field: limine_hhdm_response::offset"]
        [::core::mem::offset_of!(limine_hhdm_response, offset) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_hhdm_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_hhdm_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_hhdm_request"][::core::mem::size_of::<limine_hhdm_request>() - 48usize];
    ["Alignment of limine_hhdm_request"][::core::mem::align_of::<limine_hhdm_request>() - 8usize];
    ["Offset of field: limine_hhdm_request::id"]
        [::core::mem::offset_of!(limine_hhdm_request, id) - 0usize];
    ["Offset of field: limine_hhdm_request::revision"]
        [::core::mem::offset_of!(limine_hhdm_request, revision) - 32usize];
    ["Offset of field: limine_hhdm_request::response"]
        [::core::mem::offset_of!(limine_hhdm_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_video_mode {
    pub pitch: u64,
    pub width: u64,
    pub height: u64,
    pub bpp: u16,
    pub memory_model: u8,
    pub red_mask_size: u8,
    pub red_mask_shift: u8,
    pub green_mask_size: u8,
    pub green_mask_shift: u8,
    pub blue_mask_size: u8,
    pub blue_mask_shift: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_video_mode"][::core::mem::size_of::<limine_video_mode>() - 40usize];
    ["Alignment of limine_video_mode"][::core::mem::align_of::<limine_video_mode>() - 8usize];
    ["Offset of field: limine_video_mode::pitch"]
        [::core::mem::offset_of!(limine_video_mode, pitch) - 0usize];
    ["Offset of field: limine_video_mode::width"]
        [::core::mem::offset_of!(limine_video_mode, width) - 8usize];
    ["Offset of field: limine_video_mode::height"]
        [::core::mem::offset_of!(limine_video_mode, height) - 16usize];
    ["Offset of field: limine_video_mode::bpp"]
        [::core::mem::offset_of!(limine_video_mode, bpp) - 24usize];
    ["Offset of field: limine_video_mode::memory_model"]
        [::core::mem::offset_of!(limine_video_mode, memory_model) - 26usize];
    ["Offset of field: limine_video_mode::red_mask_size"]
        [::core::mem::offset_of!(limine_video_mode, red_mask_size) - 27usize];
    ["Offset of field: limine_video_mode::red_mask_shift"]
        [::core::mem::offset_of!(limine_video_mode, red_mask_shift) - 28usize];
    ["Offset of field: limine_video_mode::green_mask_size"]
        [::core::mem::offset_of!(limine_video_mode, green_mask_size) - 29usize];
    ["Offset of field: limine_video_mode::green_mask_shift"]
        [::core::mem::offset_of!(limine_video_mode, green_mask_shift) - 30usize];
    ["Offset of field: limine_video_mode::blue_mask_size"]
        [::core::mem::offset_of!(limine_video_mode, blue_mask_size) - 31usize];
    ["Offset of field: limine_video_mode::blue_mask_shift"]
        [::core::mem::offset_of!(limine_video_mode, blue_mask_shift) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_framebuffer {
    pub address: *mut ::core::ffi::c_void,
    pub width: u64,
    pub height: u64,
    pub pitch: u64,
    pub bpp: u16,
    pub memory_model: u8,
    pub red_mask_size: u8,
    pub red_mask_shift: u8,
    pub green_mask_size: u8,
    pub green_mask_shift: u8,
    pub blue_mask_size: u8,
    pub blue_mask_shift: u8,
    pub unused: [u8; 7usize],
    pub edid_size: u64,
    pub edid: *mut ::core::ffi::c_void,
    pub mode_count: u64,
    pub modes: *mut *mut limine_video_mode,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_framebuffer"][::core::mem::size_of::<limine_framebuffer>() - 80usize];
    ["Alignment of limine_framebuffer"][::core::mem::align_of::<limine_framebuffer>() - 8usize];
    ["Offset of field: limine_framebuffer::address"]
        [::core::mem::offset_of!(limine_framebuffer, address) - 0usize];
    ["Offset of field: limine_framebuffer::width"]
        [::core::mem::offset_of!(limine_framebuffer, width) - 8usize];
    ["Offset of field: limine_framebuffer::height"]
        [::core::mem::offset_of!(limine_framebuffer, height) - 16usize];
    ["Offset of field: limine_framebuffer::pitch"]
        [::core::mem::offset_of!(limine_framebuffer, pitch) - 24usize];
    ["Offset of field: limine_framebuffer::bpp"]
        [::core::mem::offset_of!(limine_framebuffer, bpp) - 32usize];
    ["Offset of field: limine_framebuffer::memory_model"]
        [::core::mem::offset_of!(limine_framebuffer, memory_model) - 34usize];
    ["Offset of field: limine_framebuffer::red_mask_size"]
        [::core::mem::offset_of!(limine_framebuffer, red_mask_size) - 35usize];
    ["Offset of field: limine_framebuffer::red_mask_shift"]
        [::core::mem::offset_of!(limine_framebuffer, red_mask_shift) - 36usize];
    ["Offset of field: limine_framebuffer::green_mask_size"]
        [::core::mem::offset_of!(limine_framebuffer, green_mask_size) - 37usize];
    ["Offset of field: limine_framebuffer::green_mask_shift"]
        [::core::mem::offset_of!(limine_framebuffer, green_mask_shift) - 38usize];
    ["Offset of field: limine_framebuffer::blue_mask_size"]
        [::core::mem::offset_of!(limine_framebuffer, blue_mask_size) - 39usize];
    ["Offset of field: limine_framebuffer::blue_mask_shift"]
        [::core::mem::offset_of!(limine_framebuffer, blue_mask_shift) - 40usize];
    ["Offset of field: limine_framebuffer::unused"]
        [::core::mem::offset_of!(limine_framebuffer, unused) - 41usize];
    ["Offset of field: limine_framebuffer::edid_size"]
        [::core::mem::offset_of!(limine_framebuffer, edid_size) - 48usize];
    ["Offset of field: limine_framebuffer::edid"]
        [::core::mem::offset_of!(limine_framebuffer, edid) - 56usize];
    ["Offset of field: limine_framebuffer::mode_count"]
        [::core::mem::offset_of!(limine_framebuffer, mode_count) - 64usize];
    ["Offset of field: limine_framebuffer::modes"]
        [::core::mem::offset_of!(limine_framebuffer, modes) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_framebuffer_response {
    pub revision: u64,
    pub framebuffer_count: u64,
    pub framebuffers: *mut *mut limine_framebuffer,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_framebuffer_response"]
        [::core::mem::size_of::<limine_framebuffer_response>() - 24usize];
    ["Alignment of limine_framebuffer_response"]
        [::core::mem::align_of::<limine_framebuffer_response>() - 8usize];
    ["Offset of field: limine_framebuffer_response::revision"]
        [::core::mem::offset_of!(limine_framebuffer_response, revision) - 0usize];
    ["Offset of field: limine_framebuffer_response::framebuffer_count"]
        [::core::mem::offset_of!(limine_framebuffer_response, framebuffer_count) - 8usize];
    ["Offset of field: limine_framebuffer_response::framebuffers"]
        [::core::mem::offset_of!(limine_framebuffer_response, framebuffers) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_framebuffer_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_framebuffer_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_framebuffer_request"]
        [::core::mem::size_of::<limine_framebuffer_request>() - 48usize];
    ["Alignment of limine_framebuffer_request"]
        [::core::mem::align_of::<limine_framebuffer_request>() - 8usize];
    ["Offset of field: limine_framebuffer_request::id"]
        [::core::mem::offset_of!(limine_framebuffer_request, id) - 0usize];
    ["Offset of field: limine_framebuffer_request::revision"]
        [::core::mem::offset_of!(limine_framebuffer_request, revision) - 32usize];
    ["Offset of field: limine_framebuffer_request::response"]
        [::core::mem::offset_of!(limine_framebuffer_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_flanterm_fb_init_params {
    pub canvas: *mut u32,
    pub canvas_size: u64,
    pub ansi_colours: [u32; 8usize],
    pub ansi_bright_colours: [u32; 8usize],
    pub default_bg: u32,
    pub default_fg: u32,
    pub default_bg_bright: u32,
    pub default_fg_bright: u32,
    pub font: *mut ::core::ffi::c_void,
    pub font_width: u64,
    pub font_height: u64,
    pub font_spacing: u64,
    pub font_scale_x: u64,
    pub font_scale_y: u64,
    pub margin: u64,
    pub rotation: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_flanterm_fb_init_params"]
        [::core::mem::size_of::<limine_flanterm_fb_init_params>() - 160usize];
    ["Alignment of limine_flanterm_fb_init_params"]
        [::core::mem::align_of::<limine_flanterm_fb_init_params>() - 8usize];
    ["Offset of field: limine_flanterm_fb_init_params::canvas"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, canvas) - 0usize];
    ["Offset of field: limine_flanterm_fb_init_params::canvas_size"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, canvas_size) - 8usize];
    ["Offset of field: limine_flanterm_fb_init_params::ansi_colours"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, ansi_colours) - 16usize];
    ["Offset of field: limine_flanterm_fb_init_params::ansi_bright_colours"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, ansi_bright_colours) - 48usize];
    ["Offset of field: limine_flanterm_fb_init_params::default_bg"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, default_bg) - 80usize];
    ["Offset of field: limine_flanterm_fb_init_params::default_fg"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, default_fg) - 84usize];
    ["Offset of field: limine_flanterm_fb_init_params::default_bg_bright"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, default_bg_bright) - 88usize];
    ["Offset of field: limine_flanterm_fb_init_params::default_fg_bright"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, default_fg_bright) - 92usize];
    ["Offset of field: limine_flanterm_fb_init_params::font"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, font) - 96usize];
    ["Offset of field: limine_flanterm_fb_init_params::font_width"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, font_width) - 104usize];
    ["Offset of field: limine_flanterm_fb_init_params::font_height"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, font_height) - 112usize];
    ["Offset of field: limine_flanterm_fb_init_params::font_spacing"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, font_spacing) - 120usize];
    ["Offset of field: limine_flanterm_fb_init_params::font_scale_x"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, font_scale_x) - 128usize];
    ["Offset of field: limine_flanterm_fb_init_params::font_scale_y"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, font_scale_y) - 136usize];
    ["Offset of field: limine_flanterm_fb_init_params::margin"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, margin) - 144usize];
    ["Offset of field: limine_flanterm_fb_init_params::rotation"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params, rotation) - 152usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_flanterm_fb_init_params_response {
    pub revision: u64,
    pub entry_count: u64,
    pub entries: *mut *mut limine_flanterm_fb_init_params,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_flanterm_fb_init_params_response"]
        [::core::mem::size_of::<limine_flanterm_fb_init_params_response>() - 24usize];
    ["Alignment of limine_flanterm_fb_init_params_response"]
        [::core::mem::align_of::<limine_flanterm_fb_init_params_response>() - 8usize];
    ["Offset of field: limine_flanterm_fb_init_params_response::revision"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params_response, revision) - 0usize];
    ["Offset of field: limine_flanterm_fb_init_params_response::entry_count"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params_response, entry_count) - 8usize];
    ["Offset of field: limine_flanterm_fb_init_params_response::entries"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params_response, entries) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_flanterm_fb_init_params_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_flanterm_fb_init_params_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_flanterm_fb_init_params_request"]
        [::core::mem::size_of::<limine_flanterm_fb_init_params_request>() - 48usize];
    ["Alignment of limine_flanterm_fb_init_params_request"]
        [::core::mem::align_of::<limine_flanterm_fb_init_params_request>() - 8usize];
    ["Offset of field: limine_flanterm_fb_init_params_request::id"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params_request, id) - 0usize];
    ["Offset of field: limine_flanterm_fb_init_params_request::revision"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params_request, revision) - 32usize];
    ["Offset of field: limine_flanterm_fb_init_params_request::response"]
        [::core::mem::offset_of!(limine_flanterm_fb_init_params_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_paging_mode_response {
    pub revision: u64,
    pub mode: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_paging_mode_response"]
        [::core::mem::size_of::<limine_paging_mode_response>() - 16usize];
    ["Alignment of limine_paging_mode_response"]
        [::core::mem::align_of::<limine_paging_mode_response>() - 8usize];
    ["Offset of field: limine_paging_mode_response::revision"]
        [::core::mem::offset_of!(limine_paging_mode_response, revision) - 0usize];
    ["Offset of field: limine_paging_mode_response::mode"]
        [::core::mem::offset_of!(limine_paging_mode_response, mode) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_paging_mode_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_paging_mode_response,
    pub mode: u64,
    pub max_mode: u64,
    pub min_mode: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_paging_mode_request"]
        [::core::mem::size_of::<limine_paging_mode_request>() - 72usize];
    ["Alignment of limine_paging_mode_request"]
        [::core::mem::align_of::<limine_paging_mode_request>() - 8usize];
    ["Offset of field: limine_paging_mode_request::id"]
        [::core::mem::offset_of!(limine_paging_mode_request, id) - 0usize];
    ["Offset of field: limine_paging_mode_request::revision"]
        [::core::mem::offset_of!(limine_paging_mode_request, revision) - 32usize];
    ["Offset of field: limine_paging_mode_request::response"]
        [::core::mem::offset_of!(limine_paging_mode_request, response) - 40usize];
    ["Offset of field: limine_paging_mode_request::mode"]
        [::core::mem::offset_of!(limine_paging_mode_request, mode) - 48usize];
    ["Offset of field: limine_paging_mode_request::max_mode"]
        [::core::mem::offset_of!(limine_paging_mode_request, max_mode) - 56usize];
    ["Offset of field: limine_paging_mode_request::min_mode"]
        [::core::mem::offset_of!(limine_paging_mode_request, min_mode) - 64usize];
};
pub type limine_goto_address =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut limine_mp_info)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_mp_info {
    pub processor_id: u32,
    pub lapic_id: u32,
    pub reserved: u64,
    pub goto_address: limine_goto_address,
    pub extra_argument: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_mp_info"][::core::mem::size_of::<limine_mp_info>() - 32usize];
    ["Alignment of limine_mp_info"][::core::mem::align_of::<limine_mp_info>() - 8usize];
    ["Offset of field: limine_mp_info::processor_id"]
        [::core::mem::offset_of!(limine_mp_info, processor_id) - 0usize];
    ["Offset of field: limine_mp_info::lapic_id"]
        [::core::mem::offset_of!(limine_mp_info, lapic_id) - 4usize];
    ["Offset of field: limine_mp_info::reserved"]
        [::core::mem::offset_of!(limine_mp_info, reserved) - 8usize];
    ["Offset of field: limine_mp_info::goto_address"]
        [::core::mem::offset_of!(limine_mp_info, goto_address) - 16usize];
    ["Offset of field: limine_mp_info::extra_argument"]
        [::core::mem::offset_of!(limine_mp_info, extra_argument) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_mp_response {
    pub revision: u64,
    pub flags: u32,
    pub bsp_lapic_id: u32,
    pub cpu_count: u64,
    pub cpus: *mut *mut limine_mp_info,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_mp_response"][::core::mem::size_of::<limine_mp_response>() - 32usize];
    ["Alignment of limine_mp_response"][::core::mem::align_of::<limine_mp_response>() - 8usize];
    ["Offset of field: limine_mp_response::revision"]
        [::core::mem::offset_of!(limine_mp_response, revision) - 0usize];
    ["Offset of field: limine_mp_response::flags"]
        [::core::mem::offset_of!(limine_mp_response, flags) - 8usize];
    ["Offset of field: limine_mp_response::bsp_lapic_id"]
        [::core::mem::offset_of!(limine_mp_response, bsp_lapic_id) - 12usize];
    ["Offset of field: limine_mp_response::cpu_count"]
        [::core::mem::offset_of!(limine_mp_response, cpu_count) - 16usize];
    ["Offset of field: limine_mp_response::cpus"]
        [::core::mem::offset_of!(limine_mp_response, cpus) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_mp_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_mp_response,
    pub flags: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_mp_request"][::core::mem::size_of::<limine_mp_request>() - 56usize];
    ["Alignment of limine_mp_request"][::core::mem::align_of::<limine_mp_request>() - 8usize];
    ["Offset of field: limine_mp_request::id"]
        [::core::mem::offset_of!(limine_mp_request, id) - 0usize];
    ["Offset of field: limine_mp_request::revision"]
        [::core::mem::offset_of!(limine_mp_request, revision) - 32usize];
    ["Offset of field: limine_mp_request::response"]
        [::core::mem::offset_of!(limine_mp_request, response) - 40usize];
    ["Offset of field: limine_mp_request::flags"]
        [::core::mem::offset_of!(limine_mp_request, flags) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_memmap_entry {
    pub base: u64,
    pub length: u64,
    pub type_: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_memmap_entry"][::core::mem::size_of::<limine_memmap_entry>() - 24usize];
    ["Alignment of limine_memmap_entry"][::core::mem::align_of::<limine_memmap_entry>() - 8usize];
    ["Offset of field: limine_memmap_entry::base"]
        [::core::mem::offset_of!(limine_memmap_entry, base) - 0usize];
    ["Offset of field: limine_memmap_entry::length"]
        [::core::mem::offset_of!(limine_memmap_entry, length) - 8usize];
    ["Offset of field: limine_memmap_entry::type_"]
        [::core::mem::offset_of!(limine_memmap_entry, type_) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_memmap_response {
    pub revision: u64,
    pub entry_count: u64,
    pub entries: *mut *mut limine_memmap_entry,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_memmap_response"][::core::mem::size_of::<limine_memmap_response>() - 24usize];
    ["Alignment of limine_memmap_response"]
        [::core::mem::align_of::<limine_memmap_response>() - 8usize];
    ["Offset of field: limine_memmap_response::revision"]
        [::core::mem::offset_of!(limine_memmap_response, revision) - 0usize];
    ["Offset of field: limine_memmap_response::entry_count"]
        [::core::mem::offset_of!(limine_memmap_response, entry_count) - 8usize];
    ["Offset of field: limine_memmap_response::entries"]
        [::core::mem::offset_of!(limine_memmap_response, entries) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_memmap_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_memmap_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_memmap_request"][::core::mem::size_of::<limine_memmap_request>() - 48usize];
    ["Alignment of limine_memmap_request"]
        [::core::mem::align_of::<limine_memmap_request>() - 8usize];
    ["Offset of field: limine_memmap_request::id"]
        [::core::mem::offset_of!(limine_memmap_request, id) - 0usize];
    ["Offset of field: limine_memmap_request::revision"]
        [::core::mem::offset_of!(limine_memmap_request, revision) - 32usize];
    ["Offset of field: limine_memmap_request::response"]
        [::core::mem::offset_of!(limine_memmap_request, response) - 40usize];
};
pub type limine_entry_point = ::core::option::Option<unsafe extern "C" fn()>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_entry_point_response {
    pub revision: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_entry_point_response"]
        [::core::mem::size_of::<limine_entry_point_response>() - 8usize];
    ["Alignment of limine_entry_point_response"]
        [::core::mem::align_of::<limine_entry_point_response>() - 8usize];
    ["Offset of field: limine_entry_point_response::revision"]
        [::core::mem::offset_of!(limine_entry_point_response, revision) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_entry_point_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_entry_point_response,
    pub entry: limine_entry_point,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_entry_point_request"]
        [::core::mem::size_of::<limine_entry_point_request>() - 56usize];
    ["Alignment of limine_entry_point_request"]
        [::core::mem::align_of::<limine_entry_point_request>() - 8usize];
    ["Offset of field: limine_entry_point_request::id"]
        [::core::mem::offset_of!(limine_entry_point_request, id) - 0usize];
    ["Offset of field: limine_entry_point_request::revision"]
        [::core::mem::offset_of!(limine_entry_point_request, revision) - 32usize];
    ["Offset of field: limine_entry_point_request::response"]
        [::core::mem::offset_of!(limine_entry_point_request, response) - 40usize];
    ["Offset of field: limine_entry_point_request::entry"]
        [::core::mem::offset_of!(limine_entry_point_request, entry) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_file_response {
    pub revision: u64,
    pub executable_file: *mut limine_file,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_executable_file_response"]
        [::core::mem::size_of::<limine_executable_file_response>() - 16usize];
    ["Alignment of limine_executable_file_response"]
        [::core::mem::align_of::<limine_executable_file_response>() - 8usize];
    ["Offset of field: limine_executable_file_response::revision"]
        [::core::mem::offset_of!(limine_executable_file_response, revision) - 0usize];
    ["Offset of field: limine_executable_file_response::executable_file"]
        [::core::mem::offset_of!(limine_executable_file_response, executable_file) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_file_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_executable_file_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_executable_file_request"]
        [::core::mem::size_of::<limine_executable_file_request>() - 48usize];
    ["Alignment of limine_executable_file_request"]
        [::core::mem::align_of::<limine_executable_file_request>() - 8usize];
    ["Offset of field: limine_executable_file_request::id"]
        [::core::mem::offset_of!(limine_executable_file_request, id) - 0usize];
    ["Offset of field: limine_executable_file_request::revision"]
        [::core::mem::offset_of!(limine_executable_file_request, revision) - 32usize];
    ["Offset of field: limine_executable_file_request::response"]
        [::core::mem::offset_of!(limine_executable_file_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_internal_module {
    pub path: *const ::core::ffi::c_char,
    pub string: *const ::core::ffi::c_char,
    pub flags: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_internal_module"][::core::mem::size_of::<limine_internal_module>() - 24usize];
    ["Alignment of limine_internal_module"]
        [::core::mem::align_of::<limine_internal_module>() - 8usize];
    ["Offset of field: limine_internal_module::path"]
        [::core::mem::offset_of!(limine_internal_module, path) - 0usize];
    ["Offset of field: limine_internal_module::string"]
        [::core::mem::offset_of!(limine_internal_module, string) - 8usize];
    ["Offset of field: limine_internal_module::flags"]
        [::core::mem::offset_of!(limine_internal_module, flags) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_module_response {
    pub revision: u64,
    pub module_count: u64,
    pub modules: *mut *mut limine_file,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_module_response"][::core::mem::size_of::<limine_module_response>() - 24usize];
    ["Alignment of limine_module_response"]
        [::core::mem::align_of::<limine_module_response>() - 8usize];
    ["Offset of field: limine_module_response::revision"]
        [::core::mem::offset_of!(limine_module_response, revision) - 0usize];
    ["Offset of field: limine_module_response::module_count"]
        [::core::mem::offset_of!(limine_module_response, module_count) - 8usize];
    ["Offset of field: limine_module_response::modules"]
        [::core::mem::offset_of!(limine_module_response, modules) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_module_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_module_response,
    pub internal_module_count: u64,
    pub internal_modules: *mut *mut limine_internal_module,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_module_request"][::core::mem::size_of::<limine_module_request>() - 64usize];
    ["Alignment of limine_module_request"]
        [::core::mem::align_of::<limine_module_request>() - 8usize];
    ["Offset of field: limine_module_request::id"]
        [::core::mem::offset_of!(limine_module_request, id) - 0usize];
    ["Offset of field: limine_module_request::revision"]
        [::core::mem::offset_of!(limine_module_request, revision) - 32usize];
    ["Offset of field: limine_module_request::response"]
        [::core::mem::offset_of!(limine_module_request, response) - 40usize];
    ["Offset of field: limine_module_request::internal_module_count"]
        [::core::mem::offset_of!(limine_module_request, internal_module_count) - 48usize];
    ["Offset of field: limine_module_request::internal_modules"]
        [::core::mem::offset_of!(limine_module_request, internal_modules) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_rsdp_response {
    pub revision: u64,
    pub address: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_rsdp_response"][::core::mem::size_of::<limine_rsdp_response>() - 16usize];
    ["Alignment of limine_rsdp_response"][::core::mem::align_of::<limine_rsdp_response>() - 8usize];
    ["Offset of field: limine_rsdp_response::revision"]
        [::core::mem::offset_of!(limine_rsdp_response, revision) - 0usize];
    ["Offset of field: limine_rsdp_response::address"]
        [::core::mem::offset_of!(limine_rsdp_response, address) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_rsdp_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_rsdp_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_rsdp_request"][::core::mem::size_of::<limine_rsdp_request>() - 48usize];
    ["Alignment of limine_rsdp_request"][::core::mem::align_of::<limine_rsdp_request>() - 8usize];
    ["Offset of field: limine_rsdp_request::id"]
        [::core::mem::offset_of!(limine_rsdp_request, id) - 0usize];
    ["Offset of field: limine_rsdp_request::revision"]
        [::core::mem::offset_of!(limine_rsdp_request, revision) - 32usize];
    ["Offset of field: limine_rsdp_request::response"]
        [::core::mem::offset_of!(limine_rsdp_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_smbios_response {
    pub revision: u64,
    pub entry_32: *mut ::core::ffi::c_void,
    pub entry_64: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_smbios_response"][::core::mem::size_of::<limine_smbios_response>() - 24usize];
    ["Alignment of limine_smbios_response"]
        [::core::mem::align_of::<limine_smbios_response>() - 8usize];
    ["Offset of field: limine_smbios_response::revision"]
        [::core::mem::offset_of!(limine_smbios_response, revision) - 0usize];
    ["Offset of field: limine_smbios_response::entry_32"]
        [::core::mem::offset_of!(limine_smbios_response, entry_32) - 8usize];
    ["Offset of field: limine_smbios_response::entry_64"]
        [::core::mem::offset_of!(limine_smbios_response, entry_64) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_smbios_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_smbios_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_smbios_request"][::core::mem::size_of::<limine_smbios_request>() - 48usize];
    ["Alignment of limine_smbios_request"]
        [::core::mem::align_of::<limine_smbios_request>() - 8usize];
    ["Offset of field: limine_smbios_request::id"]
        [::core::mem::offset_of!(limine_smbios_request, id) - 0usize];
    ["Offset of field: limine_smbios_request::revision"]
        [::core::mem::offset_of!(limine_smbios_request, revision) - 32usize];
    ["Offset of field: limine_smbios_request::response"]
        [::core::mem::offset_of!(limine_smbios_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_system_table_response {
    pub revision: u64,
    pub address: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_efi_system_table_response"]
        [::core::mem::size_of::<limine_efi_system_table_response>() - 16usize];
    ["Alignment of limine_efi_system_table_response"]
        [::core::mem::align_of::<limine_efi_system_table_response>() - 8usize];
    ["Offset of field: limine_efi_system_table_response::revision"]
        [::core::mem::offset_of!(limine_efi_system_table_response, revision) - 0usize];
    ["Offset of field: limine_efi_system_table_response::address"]
        [::core::mem::offset_of!(limine_efi_system_table_response, address) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_system_table_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_efi_system_table_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_efi_system_table_request"]
        [::core::mem::size_of::<limine_efi_system_table_request>() - 48usize];
    ["Alignment of limine_efi_system_table_request"]
        [::core::mem::align_of::<limine_efi_system_table_request>() - 8usize];
    ["Offset of field: limine_efi_system_table_request::id"]
        [::core::mem::offset_of!(limine_efi_system_table_request, id) - 0usize];
    ["Offset of field: limine_efi_system_table_request::revision"]
        [::core::mem::offset_of!(limine_efi_system_table_request, revision) - 32usize];
    ["Offset of field: limine_efi_system_table_request::response"]
        [::core::mem::offset_of!(limine_efi_system_table_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_tpm_event_log_response {
    pub revision: u64,
    pub format: u64,
    pub size: u64,
    pub address: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_tpm_event_log_response"]
        [::core::mem::size_of::<limine_tpm_event_log_response>() - 32usize];
    ["Alignment of limine_tpm_event_log_response"]
        [::core::mem::align_of::<limine_tpm_event_log_response>() - 8usize];
    ["Offset of field: limine_tpm_event_log_response::revision"]
        [::core::mem::offset_of!(limine_tpm_event_log_response, revision) - 0usize];
    ["Offset of field: limine_tpm_event_log_response::format"]
        [::core::mem::offset_of!(limine_tpm_event_log_response, format) - 8usize];
    ["Offset of field: limine_tpm_event_log_response::size"]
        [::core::mem::offset_of!(limine_tpm_event_log_response, size) - 16usize];
    ["Offset of field: limine_tpm_event_log_response::address"]
        [::core::mem::offset_of!(limine_tpm_event_log_response, address) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_tpm_event_log_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_tpm_event_log_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_tpm_event_log_request"]
        [::core::mem::size_of::<limine_tpm_event_log_request>() - 48usize];
    ["Alignment of limine_tpm_event_log_request"]
        [::core::mem::align_of::<limine_tpm_event_log_request>() - 8usize];
    ["Offset of field: limine_tpm_event_log_request::id"]
        [::core::mem::offset_of!(limine_tpm_event_log_request, id) - 0usize];
    ["Offset of field: limine_tpm_event_log_request::revision"]
        [::core::mem::offset_of!(limine_tpm_event_log_request, revision) - 32usize];
    ["Offset of field: limine_tpm_event_log_request::response"]
        [::core::mem::offset_of!(limine_tpm_event_log_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_memmap_response {
    pub revision: u64,
    pub memmap: *mut ::core::ffi::c_void,
    pub memmap_size: u64,
    pub desc_size: u64,
    pub desc_version: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_efi_memmap_response"]
        [::core::mem::size_of::<limine_efi_memmap_response>() - 40usize];
    ["Alignment of limine_efi_memmap_response"]
        [::core::mem::align_of::<limine_efi_memmap_response>() - 8usize];
    ["Offset of field: limine_efi_memmap_response::revision"]
        [::core::mem::offset_of!(limine_efi_memmap_response, revision) - 0usize];
    ["Offset of field: limine_efi_memmap_response::memmap"]
        [::core::mem::offset_of!(limine_efi_memmap_response, memmap) - 8usize];
    ["Offset of field: limine_efi_memmap_response::memmap_size"]
        [::core::mem::offset_of!(limine_efi_memmap_response, memmap_size) - 16usize];
    ["Offset of field: limine_efi_memmap_response::desc_size"]
        [::core::mem::offset_of!(limine_efi_memmap_response, desc_size) - 24usize];
    ["Offset of field: limine_efi_memmap_response::desc_version"]
        [::core::mem::offset_of!(limine_efi_memmap_response, desc_version) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_memmap_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_efi_memmap_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_efi_memmap_request"]
        [::core::mem::size_of::<limine_efi_memmap_request>() - 48usize];
    ["Alignment of limine_efi_memmap_request"]
        [::core::mem::align_of::<limine_efi_memmap_request>() - 8usize];
    ["Offset of field: limine_efi_memmap_request::id"]
        [::core::mem::offset_of!(limine_efi_memmap_request, id) - 0usize];
    ["Offset of field: limine_efi_memmap_request::revision"]
        [::core::mem::offset_of!(limine_efi_memmap_request, revision) - 32usize];
    ["Offset of field: limine_efi_memmap_request::response"]
        [::core::mem::offset_of!(limine_efi_memmap_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_date_at_boot_response {
    pub revision: u64,
    pub timestamp: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_date_at_boot_response"]
        [::core::mem::size_of::<limine_date_at_boot_response>() - 16usize];
    ["Alignment of limine_date_at_boot_response"]
        [::core::mem::align_of::<limine_date_at_boot_response>() - 8usize];
    ["Offset of field: limine_date_at_boot_response::revision"]
        [::core::mem::offset_of!(limine_date_at_boot_response, revision) - 0usize];
    ["Offset of field: limine_date_at_boot_response::timestamp"]
        [::core::mem::offset_of!(limine_date_at_boot_response, timestamp) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_date_at_boot_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_date_at_boot_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_date_at_boot_request"]
        [::core::mem::size_of::<limine_date_at_boot_request>() - 48usize];
    ["Alignment of limine_date_at_boot_request"]
        [::core::mem::align_of::<limine_date_at_boot_request>() - 8usize];
    ["Offset of field: limine_date_at_boot_request::id"]
        [::core::mem::offset_of!(limine_date_at_boot_request, id) - 0usize];
    ["Offset of field: limine_date_at_boot_request::revision"]
        [::core::mem::offset_of!(limine_date_at_boot_request, revision) - 32usize];
    ["Offset of field: limine_date_at_boot_request::response"]
        [::core::mem::offset_of!(limine_date_at_boot_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_address_response {
    pub revision: u64,
    pub physical_base: u64,
    pub virtual_base: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_executable_address_response"]
        [::core::mem::size_of::<limine_executable_address_response>() - 24usize];
    ["Alignment of limine_executable_address_response"]
        [::core::mem::align_of::<limine_executable_address_response>() - 8usize];
    ["Offset of field: limine_executable_address_response::revision"]
        [::core::mem::offset_of!(limine_executable_address_response, revision) - 0usize];
    ["Offset of field: limine_executable_address_response::physical_base"]
        [::core::mem::offset_of!(limine_executable_address_response, physical_base) - 8usize];
    ["Offset of field: limine_executable_address_response::virtual_base"]
        [::core::mem::offset_of!(limine_executable_address_response, virtual_base) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_address_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_executable_address_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_executable_address_request"]
        [::core::mem::size_of::<limine_executable_address_request>() - 48usize];
    ["Alignment of limine_executable_address_request"]
        [::core::mem::align_of::<limine_executable_address_request>() - 8usize];
    ["Offset of field: limine_executable_address_request::id"]
        [::core::mem::offset_of!(limine_executable_address_request, id) - 0usize];
    ["Offset of field: limine_executable_address_request::revision"]
        [::core::mem::offset_of!(limine_executable_address_request, revision) - 32usize];
    ["Offset of field: limine_executable_address_request::response"]
        [::core::mem::offset_of!(limine_executable_address_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_dtb_response {
    pub revision: u64,
    pub dtb_ptr: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_dtb_response"][::core::mem::size_of::<limine_dtb_response>() - 16usize];
    ["Alignment of limine_dtb_response"][::core::mem::align_of::<limine_dtb_response>() - 8usize];
    ["Offset of field: limine_dtb_response::revision"]
        [::core::mem::offset_of!(limine_dtb_response, revision) - 0usize];
    ["Offset of field: limine_dtb_response::dtb_ptr"]
        [::core::mem::offset_of!(limine_dtb_response, dtb_ptr) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_dtb_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_dtb_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_dtb_request"][::core::mem::size_of::<limine_dtb_request>() - 48usize];
    ["Alignment of limine_dtb_request"][::core::mem::align_of::<limine_dtb_request>() - 8usize];
    ["Offset of field: limine_dtb_request::id"]
        [::core::mem::offset_of!(limine_dtb_request, id) - 0usize];
    ["Offset of field: limine_dtb_request::revision"]
        [::core::mem::offset_of!(limine_dtb_request, revision) - 32usize];
    ["Offset of field: limine_dtb_request::response"]
        [::core::mem::offset_of!(limine_dtb_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_riscv_bsp_hartid_response {
    pub revision: u64,
    pub bsp_hartid: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_riscv_bsp_hartid_response"]
        [::core::mem::size_of::<limine_riscv_bsp_hartid_response>() - 16usize];
    ["Alignment of limine_riscv_bsp_hartid_response"]
        [::core::mem::align_of::<limine_riscv_bsp_hartid_response>() - 8usize];
    ["Offset of field: limine_riscv_bsp_hartid_response::revision"]
        [::core::mem::offset_of!(limine_riscv_bsp_hartid_response, revision) - 0usize];
    ["Offset of field: limine_riscv_bsp_hartid_response::bsp_hartid"]
        [::core::mem::offset_of!(limine_riscv_bsp_hartid_response, bsp_hartid) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_riscv_bsp_hartid_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_riscv_bsp_hartid_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_riscv_bsp_hartid_request"]
        [::core::mem::size_of::<limine_riscv_bsp_hartid_request>() - 48usize];
    ["Alignment of limine_riscv_bsp_hartid_request"]
        [::core::mem::align_of::<limine_riscv_bsp_hartid_request>() - 8usize];
    ["Offset of field: limine_riscv_bsp_hartid_request::id"]
        [::core::mem::offset_of!(limine_riscv_bsp_hartid_request, id) - 0usize];
    ["Offset of field: limine_riscv_bsp_hartid_request::revision"]
        [::core::mem::offset_of!(limine_riscv_bsp_hartid_request, revision) - 32usize];
    ["Offset of field: limine_riscv_bsp_hartid_request::response"]
        [::core::mem::offset_of!(limine_riscv_bsp_hartid_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_performance_response {
    pub revision: u64,
    pub reset_usec: u64,
    pub init_usec: u64,
    pub exec_usec: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_bootloader_performance_response"]
        [::core::mem::size_of::<limine_bootloader_performance_response>() - 32usize];
    ["Alignment of limine_bootloader_performance_response"]
        [::core::mem::align_of::<limine_bootloader_performance_response>() - 8usize];
    ["Offset of field: limine_bootloader_performance_response::revision"]
        [::core::mem::offset_of!(limine_bootloader_performance_response, revision) - 0usize];
    ["Offset of field: limine_bootloader_performance_response::reset_usec"]
        [::core::mem::offset_of!(limine_bootloader_performance_response, reset_usec) - 8usize];
    ["Offset of field: limine_bootloader_performance_response::init_usec"]
        [::core::mem::offset_of!(limine_bootloader_performance_response, init_usec) - 16usize];
    ["Offset of field: limine_bootloader_performance_response::exec_usec"]
        [::core::mem::offset_of!(limine_bootloader_performance_response, exec_usec) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_performance_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_bootloader_performance_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_bootloader_performance_request"]
        [::core::mem::size_of::<limine_bootloader_performance_request>() - 48usize];
    ["Alignment of limine_bootloader_performance_request"]
        [::core::mem::align_of::<limine_bootloader_performance_request>() - 8usize];
    ["Offset of field: limine_bootloader_performance_request::id"]
        [::core::mem::offset_of!(limine_bootloader_performance_request, id) - 0usize];
    ["Offset of field: limine_bootloader_performance_request::revision"]
        [::core::mem::offset_of!(limine_bootloader_performance_request, revision) - 32usize];
    ["Offset of field: limine_bootloader_performance_request::response"]
        [::core::mem::offset_of!(limine_bootloader_performance_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_x86_64_keep_iommu_response {
    pub revision: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_x86_64_keep_iommu_response"]
        [::core::mem::size_of::<limine_x86_64_keep_iommu_response>() - 8usize];
    ["Alignment of limine_x86_64_keep_iommu_response"]
        [::core::mem::align_of::<limine_x86_64_keep_iommu_response>() - 8usize];
    ["Offset of field: limine_x86_64_keep_iommu_response::revision"]
        [::core::mem::offset_of!(limine_x86_64_keep_iommu_response, revision) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_x86_64_keep_iommu_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_x86_64_keep_iommu_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_x86_64_keep_iommu_request"]
        [::core::mem::size_of::<limine_x86_64_keep_iommu_request>() - 48usize];
    ["Alignment of limine_x86_64_keep_iommu_request"]
        [::core::mem::align_of::<limine_x86_64_keep_iommu_request>() - 8usize];
    ["Offset of field: limine_x86_64_keep_iommu_request::id"]
        [::core::mem::offset_of!(limine_x86_64_keep_iommu_request, id) - 0usize];
    ["Offset of field: limine_x86_64_keep_iommu_request::revision"]
        [::core::mem::offset_of!(limine_x86_64_keep_iommu_request, revision) - 32usize];
    ["Offset of field: limine_x86_64_keep_iommu_request::response"]
        [::core::mem::offset_of!(limine_x86_64_keep_iommu_request, response) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_tsc_frequency_response {
    pub revision: u64,
    pub frequency: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_tsc_frequency_response"]
        [::core::mem::size_of::<limine_tsc_frequency_response>() - 16usize];
    ["Alignment of limine_tsc_frequency_response"]
        [::core::mem::align_of::<limine_tsc_frequency_response>() - 8usize];
    ["Offset of field: limine_tsc_frequency_response::revision"]
        [::core::mem::offset_of!(limine_tsc_frequency_response, revision) - 0usize];
    ["Offset of field: limine_tsc_frequency_response::frequency"]
        [::core::mem::offset_of!(limine_tsc_frequency_response, frequency) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_tsc_frequency_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_tsc_frequency_response,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of limine_tsc_frequency_request"]
        [::core::mem::size_of::<limine_tsc_frequency_request>() - 48usize];
    ["Alignment of limine_tsc_frequency_request"]
        [::core::mem::align_of::<limine_tsc_frequency_request>() - 8usize];
    ["Offset of field: limine_tsc_frequency_request::id"]
        [::core::mem::offset_of!(limine_tsc_frequency_request, id) - 0usize];
    ["Offset of field: limine_tsc_frequency_request::revision"]
        [::core::mem::offset_of!(limine_tsc_frequency_request, revision) - 32usize];
    ["Offset of field: limine_tsc_frequency_request::response"]
        [::core::mem::offset_of!(limine_tsc_frequency_request, response) - 40usize];
};
unsafe extern "C" {
    pub fn phys_to_hhdm(phys: u64) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Sets up physical RAM, by allocating a region to track which pages are free\n\n Also Sets up archaic paginging things, and allows interrupts to work properly"]
    pub fn memory_init();
}
unsafe extern "C" {
    #[doc = " Copies the original kernel page tables, and returns the physical address of the tree's root (set CR3 to point at them)"]
    pub fn generate_clean_virtual_addressing() -> u64;
}
unsafe extern "C" {
    #[doc = " Removes the page table' userland pages under the current virtual addressing. sets CR3 back to a default (the original kernel page tables)"]
    pub fn remove_virtual_addressing();
}
unsafe extern "C" {
    #[doc = " Keeps the kernel page table pointers, but clones the data and page tree, returning physical address of new page table tree"]
    pub fn clone_virtual_addressing(original_root_phys: u64) -> u64;
}
unsafe extern "C" {
    #[doc = " Sets CR3 to point at the root of a page table tree"]
    pub fn set_pml4_phys(physical_addr: u64);
}
unsafe extern "C" {
    #[doc = " Gets CR3, returning a physical address of the root of the page table tree"]
    pub fn get_pml4_phys() -> u64;
}
unsafe extern "C" {
    #[doc = " @brief allocates and zeroes a new page, and you can pick what the address is\n @param virtual_addr virtual address of the start of an unmapped page"]
    pub fn allocate_ram_page(virtual_addr: *mut ::core::ffi::c_void, can_execute: bool);
}
unsafe extern "C" {
    pub fn setup_mmio(phys_addr: u64, size: u64) -> *mut ::core::ffi::c_void;
}
