#ifndef XHCI_TRB_H
#define XHCI_TRB_H

#include "uapi/stdint.h"

#define TRB_TYPE_NORMAL 1
#define TRB_TYPE_SETUP_STAGE 2
#define TRB_TYPE_DATA_STAGE 3
#define TRB_TYPE_STATUS_STAGE 4
#define TRB_TYPE_LINK 6
#define TRB_TYPE_EVENT_DATA 7
#define TRB_TYPE_ENABLE_SLOT 9
#define TRB_TYPE_SET_ADDRESS 11
//adds or removes endpoints, but can't modify existing ones
#define TRB_TYPE_CONFIGURE_ENDPOINT 12
//changes the settings of an already-configured endpoint (cannot be used to create/delete endpoints)
#define TRB_TYPE_EVALUATE_CONTEXT 13

//event ring responses types
#define TRB_TYPE_TRANSFER 32
#define TRB_TYPE_CMD_COMPLETION 33
#define TRB_TYPE_PORT_STS_CHANGE 34
//optional
#define TRB_TYPE_BANDWIDTH_REQUEST 35
//optional
#define TRB_TYPE_DOORBELL 36
#define TRB_TYPE_HOST_CONTROLLER 37
#define TRB_TYPE_DEVICE_NOTIFICATION 38
#define TRB_TYPE_MFINDEX_WRAP 39

//toggle the internal cycle bit
#define TRB_TC_BIT (1 << 1)

#define DESCRIPTOR_TYPE_DEVICE 1
#define DESCRIPTOR_TYPE_CONFIGURATION 2
#define DESCRIPTOR_TYPE_STRING 3
#define DESCRIPTOR_TYPE_INTERFACE 4
#define DESCRIPTOR_TYPE_ENDPOINT 5
// #define DESCRIPTOR_TYPE_DEVICE_QUALIFIER 6
// #define DESCRIPTOR_TYPE_OTHER_SPEED_CONFIGURATION 7
// #define DESCRIPTOR_TYPE_INTERFACE_POWER 8

struct TRB {
    union {
        uint64_t raw;

        struct DeviceRequestPacket {
            uint64_t
            //0=>device, 1=>interface, 2=>endpoint, 3=>other
            recipient: 5,
            //0=>standard, 1=>class, 2=>vendor
            type: 2,
            //0=>host to device, 1=>device to host
            direction: 1,
            //see appendix G on the USB book. 6=>get descriptor
            request: 8,
            value: 16,
            index: 16,
            //if a data phase, num of bytes to transfer
            length: 16;
        } device_request;
    } parameter;

    union {
        uint64_t raw;
        //minimal
        struct {
            uint64_t
            reserved_0: 32,
            cycle_bit: 1,
            reserved_1: 9,
            trb_type: 6,
            reserved_2: 16;
        };

        struct NormalTRB {
            uint64_t
            trb_transfer_length: 16,
            td_size:5,
            interrupter_target: 10,
            cycle_bit: 1,
            evaluate_next_trb: 1,
            interrupt_on_short_packet: 1,
            no_snoop: 1,
            chain_bit: 1,
            interrupt_on_completion: 1,
            immediate_data: 1,
            reserved_0: 2,
            block_event_interrupt: 1,
            trb_type: 6,
            reserved_1: 16;
        } normal;

        struct LinkTRBSts {
            uint64_t
            reserved_0: 22,
            interrupter_target: 10,
            cycle_bit: 1,
            toggle_cycle: 1,
            reserved_1: 2,
            chain_bit: 1,
            interrupt_on_completion: 1,
            reserved_2: 4,
            trb_type: 6,
            reserved_3: 16;
        } link;

        struct CommandCompletionEvent {
            uint64_t
            command_completion_parameter: 24,
            completion_code: 8,
            cycle_bit: 1,
            reserved_0: 9,
            trb_type: 6,
            vf_id: 8,
            slot_id: 8;
        } command_completion;

        //aka transfer event
        struct TypeTransfer {
            uint64_t
            trb_transfer_length: 24,
            completion_code: 8,
            cycle_bit: 1,
            reserved_0: 1,
            //1=> generated by event data TRB and the parameter contains value from the event data TRB, 0=>parameter contains pointer to the TRB that generated the event
            event_data: 1,
            reserved_1: 7,
            trb_type: 6,
            endpoint_id: 5,
            reserved_2: 3,
            slot_id: 8;
        } type_transfer;

        struct SetAddressCommand {
            uint64_t
            reserved_0: 32,
            cycle_bit: 1,
            reserved_1: 8,
            block_set_address_request: 1,//BSR
            trb_type: 6,
            reserved_2: 8,
            slot_id: 8;
        } set_address;

        struct DeviceRequestSts {
            uint64_t
            trb_transfer_length: 17,
            reserved_0: 5,
            interrupter_target: 10,
            cycle_bit: 1,
            reserved_1: 4,
            interrupt_on_completion: 1,
            immediate_data: 1,
            reserved_2: 3,
            trb_type: 6,
            //0=>no data stage, 2=>OUT data stage, 3=>IN data stage
            transfer_type: 2,
            reserved_3: 14;
        } device_request;

        struct DataStage {
            uint64_t
            trb_transfer_length: 17,
            td_size: 5,
            interrupter_target: 10,
            cycle_bit: 1,
            evaluate_next_trb: 1,
            interrupt_on_short_packet: 1,
            no_snoop: 1,
            chain_bit: 1,
            interrupt_on_completion: 1,
            immediate_data: 1,
            reserved_0: 3,
            trb_type: 6,
            //(unsure) 1=>to OS, 2=>from OS
            direction: 1,
            reserved_1: 15;
        } data_stage;

        struct EventData {
            uint64_t
            reserved_0: 24,
            interrupt_target: 8,
            cycle_bit: 1,
            evaluate_next_trb: 1,
            reserved_1: 2,
            chain_bit: 1,
            interrupt_on_completion: 1,
            reserved_2: 3,
            block_event_interrupt: 1,
            trb_type: 6,
            reserved_3: 16;
        } event_data;

        struct StatusStage {
            uint64_t
            reserved_0: 22,
            interrupter_target: 10,
            cycle_bit: 1,
            evaluate_next_trb: 1,
            reserved_1: 2,
            chain_bit: 1,
            interrupt_on_completion: 1,
            reserved_2: 4,
            trb_type: 6,
            direction: 1,
            reserved_3: 15;
        } status_stage;
    } status;
};

struct Ring {
    uint64_t count;
    uint64_t idx;
    uint64_t trbs_phys;
    // NULL indicates an uninitialised ring
    struct TRB *trbs;
    uint8_t ring_cycle_state;
};

struct Ring create_ring();
void enqueue_ring(struct Ring *ring, struct TRB trb);
//returns 0 on success, -1 if there was nothing to get (trb_out unaffected)
int dequeue_ring(struct Ring *ring, struct TRB *trb_out);

#endif